package main;
import java.util.stream.IntStream;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Factorial {
    public static int factorial(int value) {
    	if(value == 0)
    		return 1;
    	if(value < 3)
    		return value;
    	
    	return IntStream.rangeClosed(1, value).reduce(1, (i,j) -> i*j);
    } 
}
