package sam.learn.spock.fire;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class FireEarlyWarning {
    private int sensorsDetectingFire = 0;
    
    public void feedData(int triggeredFireSensors) {
		this.sensorsDetectingFire = triggeredFireSensors;
	}
    public WarningStatus getCurrentStatus() {
    	return new WarningStatus(sensorsDetectingFire > 0, sensorsDetectingFire > 1); 
    }
}
